name: Build and Deploy Marketing
on: [push]
permissions:
    contents: write
jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install and Build
              working-directory: ./marketing-next
              run: |
                  npm ci
                  npm run build
                  npm run export
                  touch ./out/.nojekyll

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.MARKETING_DEPLOY_PAT }}
                  folder: ./marketing-next/out
                  branch: main
                  repository-name: bulwarkid/bulwark-passkey-website
